# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_name = Dynamic Surroundings
mod_description = Alters the fabric of Minecraft experience by weaving a tapestry of sound and visual effects
mod_version = 26.1-1.0.0
mod_author = Astryxion
mod_credits = OreCruncher, Sound Contributors
mod_license = MIT
mod_issues_url = https://github.com/astryxion/Dynamic-Surroundings/issues
mod_homepage_url = https://github.com/astryxion/Dynamic-Surroundings
maven_group = org.orecruncher
archives_name = dynamicsurroundings
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
architectury_api_version = 20.0.12
fabric_loader_version = 0.19.2
fabric_api_version = 0.155.2+26.1.2
neoforge_version = 26.1.2.70-beta
nashorn_version = 15.4
glitchcore_version = 26.1.2.0.0
serene_seasons_version = 26.1.2.0.4
bop_version = 26.1.2.0.21
terrablender_version = 26.1.2.0.3
clothapi_version = 26.1.154
yacl_version = 3.6.1+1.21
modmenu_version = 18.0.0
