# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_name = Dynamic Surroundings
mod_description = Alters the fabric of Minecraft experience by weaving a tapestry of sound and visual effects
mod_version = 1.21.11-1.0.0
mod_author = Astryxion
mod_credits = OreCruncher, Sound Contributors
mod_license = MIT
mod_issues_url = https://github.com/astryxion/Dynamic-Surroundings/issues
mod_homepage_url = https://github.com/astryxion/Dynamic-Surroundings
maven_group = org.orecruncher
archives_name = dynamicsurroundings
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.11

# Dependencies
architectury_api_version = 19.0.1
fabric_loader_version = 0.19.5
fabric_api_version = 0.141.5+1.21.11
neoforge_version = 21.11.45
mixinextras_version = 0.5.5
nashorn_version = 15.4
glitchcore_version = 21.11.0.2
serene_seasons_version = 21.11.0.4
bop_version = 21.11.0.32
terrablender_version = 21.11.0.0
clothapi_version = 21.11.153
yacl_version = 3.6.1+1.21
modmenu_version = 17.0.0
